# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  build:
    dir: ./
    cmds:
      - "zig build -Doptimize=ReleaseFast"
      - "cp ./zig-out/bin/coglife_wasm.wasm ./browser/"

  build:dev:
    cmds:
      - "zig build -Doptimize=Debug"

  web:
    deps: [build]
    dir: ./browser
    cmds:
      - "python3 -m http.server"
     
  preview:
    deps: [build]
    cmds:
      - "./zig-out/bin/coglife --rows=10 --columns=10 --sleep=200"

  bench:
    deps: [build]
    cmds:
      - time ./zig-out/bin/coglife --generations=60 --sleep=0 --no-render --rows=2169 --columns=3840
